# Generated by Django 3.1.2 on 2020-12-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created'], 'verbose_name_plural': 'servicios'},
        ),
    ]
