# Generated by Django 3.1.2 on 2020-10-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='Key',
            new_name='key',
        ),
    ]
